"""Full grammar reference for Final Touch sentence detail prompts.

This module stores the teacher-provided 1-200 grammar reference table in a
structured form.  The analyzer uses it as prompt context, and grammar_points may
surface `reference_no` values in the Flutter UI.
"""

from __future__ import annotations

GRAMMAR_REFERENCE = [{'reference_no': 1,
  'title': '주어 + 수식어구',
  'explanation': '주어 뒤에 of + 명사, 전치사구, 관계절 같은 수식어구가 길게 붙어도 동사는 수식어구가 아니라 핵심 주어의 수에 맞춘다.',
  'example': 'The nature of the jobs is important.'},
 {'reference_no': 2,
  'title': 'the number of / a number of',
  'explanation': 'the number of는 “~의 수”가 주어이므로 단수동사를 쓰고, a number of는 “많은 ~들”이라는 뜻이므로 복수동사를 쓴다.',
  'example': 'The number of students is increasing. / A number of students are absent.'},
 {'reference_no': 3,
  'title': '주격 관계대명사의 수일치',
  'explanation': 'who, which, that 같은 주격 관계대명사 뒤의 동사는 관계대명사가 꾸미는 선행사의 수에 맞춘다.',
  'example': 'There are many stars that are hotter than the sun.'},
 {'reference_no': 4,
  'title': '부분표현 + of + 명사',
  'explanation': 'some, most, all, percent, the rest, the majority 같은 부분표현은 of 뒤 명사의 수를 보고 동사의 수를 '
                 '결정한다.',
  'example': 'Some of the research is useful. / Some of the students are tired.'},
 {'reference_no': 5,
  'title': 'one of + 복수명사',
  'explanation': 'one of + 복수명사가 주어로 쓰이면 진짜 주어는 one이므로 단수동사를 쓴다.',
  'example': 'One of the features is important.'},
 {'reference_no': 6,
  'title': '상관접속사 수일치',
  'explanation': 'not only A but also B, either A or B, neither A nor B는 보통 동사와 더 가까운 주어의 수에 맞춰 '
                 '동사를 쓴다.',
  'example': 'Not only you but also she has a plan.'},
 {'reference_no': 7,
  'title': 'both A and B',
  'explanation': 'both A and B는 “A와 B 둘 다”라는 뜻이므로 주어로 쓰이면 복수동사를 쓴다.',
  'example': 'Both a written test and a practical exam are necessary.'},
 {'reference_no': 8,
  'title': 'every/each + 단수명사',
  'explanation': 'every와 each는 “각각의 하나하나”를 뜻하므로 뒤에는 단수명사를 쓰고 동사도 단수로 쓴다.',
  'example': 'Each stone block weighs more than two tons.'},
 {'reference_no': 9,
  'title': 'each of + 복수명사',
  'explanation': 'each of 뒤에는 복수명사가 오지만 주어는 each이므로 단수동사를 쓴다.',
  'example': 'Each of the students has talent.'},
 {'reference_no': 10,
  'title': '능동태 vs 수동태',
  'explanation': '주어가 동작을 직접 하면 능동태를 쓰고, 주어가 동작을 당하면 be동사 + p.p. 형태의 수동태를 쓴다.',
  'example': 'Water absorbs heat. / Heat is absorbed by water.'},
 {'reference_no': 11,
  'title': '능동태와 목적어',
  'explanation': '능동태는 목적어를 가질 수 있지만, 수동태는 원래 목적어가 주어로 이동했기 때문에 뒤에 목적어가 바로 오면 어색한 경우가 많다.',
  'example': 'He wrote the book. / The book was written.'},
 {'reference_no': 12,
  'title': '자동사의 능동/수동',
  'explanation': '자동사는 목적어를 필요로 하지 않으므로 목적어를 바로 붙일 수 없고, 원칙적으로 수동태로 만들 수 없다.',
  'example': 'He arrived at school. / arrive the school은 틀린 표현이다.'},
 {'reference_no': 13,
  'title': '4형식 문장의 능동/수동',
  'explanation': '4형식 능동태는 목적어가 2개 오지만, 수동태가 되면 목적어 하나가 주어가 되어 남은 목적어는 보통 1개만 온다.',
  'example': 'He gave me a book. / I was given a book.'},
 {'reference_no': 14,
  'title': '복잡한 구문에서의 능동/수동',
  'explanation': '관계절이나 긴 수식어가 있어도 동사와 연결되는 진짜 주어를 찾아 능동인지 수동인지 판단한다.',
  'example': 'The plant that was eaten was poisonous.'},
 {'reference_no': 15,
  'title': '감정동사 -ing / -ed',
  'explanation': '감정을 일으키는 대상은 -ing를 쓰고, 감정을 느끼는 사람은 p.p. 또는 -ed 형태를 쓴다.',
  'example': 'The news was surprising. / I was surprised.'},
 {'reference_no': 16,
  'title': 'be used to-v / be used to v-ing',
  'explanation': 'be used to-v는 “~하는 데 사용되다”라는 뜻이고, be used to v-ing는 “~하는 데 익숙하다”라는 뜻이다.',
  'example': 'Plastic is used to make clothes. / He is used to making decisions.'},
 {'reference_no': 17,
  'title': 'used to-v',
  'explanation': 'used to-v는 과거에는 자주 했지만 지금은 그렇지 않은 과거의 습관이나 상태를 나타낸다.',
  'example': 'Tom used to study every night.'},
 {'reference_no': 18,
  'title': '목적어가 명사절인 문장의 수동태',
  'explanation': 'think, believe, say, consider 같은 동사는 목적어로 that절을 받을 수 있고, 수동태에서는 It is p.p. that '
                 '~ 또는 주어 + be p.p. + to-v 형태로 바꿀 수 있다.',
  'example': 'It is thought that sunlight is damaging. / Sunlight is thought to be damaging.'},
 {'reference_no': 19,
  'title': '구동사의 수동태',
  'explanation': 'look after, deal with, pay attention to 같은 구동사는 하나의 동사처럼 취급하므로 수동태가 되어도 전치사나 부사를 '
                 '빠뜨리지 않는다.',
  'example': 'The children must be looked after.'},
 {'reference_no': 20,
  'title': '부정어구 도치',
  'explanation': 'never, little, seldom, only then 같은 부정어나 제한 표현이 문장 앞에 오면 조동사 + 주어 + 동사 어순으로 '
                 '도치된다.',
  'example': 'Never has he experienced such care.'},
 {'reference_no': 21,
  'title': '장소·방향 부사구 도치',
  'explanation': 'inside, down, up 같은 장소나 방향 표현이 문장 앞에 오면 동사 + 주어 어순으로 도치될 수 있다.',
  'example': 'Inside the pocket were several coins.'},
 {'reference_no': 22,
  'title': '보어 도치',
  'explanation': '보어가 강조되어 문장 앞에 오면 보어 + 동사 + 주어 어순으로 쓸 수 있다.',
  'example': 'Happy are those who know the pleasure of doing good.'},
 {'reference_no': 23,
  'title': 'There/Here 도치',
  'explanation': 'There나 Here가 문장 앞에 오면 보통 동사 + 주어 어순이 되지만, 주어가 대명사이면 도치하지 않는다.',
  'example': 'Here comes the bus. / Here they come.'},
 {'reference_no': 24,
  'title': '도치하지 않는 경우',
  'explanation': '문장 앞의 표현이 주어를 수식하거나 관계절 안에 있으면 주어와 동사를 도치하지 않는다.',
  'example': 'Only 15% of adults say they trust the information.'},
 {'reference_no': 25,
  'title': '간접의문문',
  'explanation': '의문문이 다른 문장의 일부로 쓰이면 의문사 + 주어 + 동사의 평서문 어순을 쓴다.',
  'example': 'I wonder where I can buy this album.'},
 {'reference_no': 26,
  'title': '생각·추측 동사의 의문문',
  'explanation': 'think, believe, guess, suppose가 쓰인 의문문에서는 의문사를 문장 맨 앞으로 보내고 뒤에는 do you think + '
                 '주어 + 동사 어순을 쓴다.',
  'example': 'What do you think the world would be like?'},
 {'reference_no': 27,
  'title': '보어 자리의 형용사',
  'explanation': '보어는 주어나 목적어의 상태를 설명하므로 형용사를 쓰고, 부사는 쓰지 않는다.',
  'example': 'I’m less aggressive than my brothers.'},
 {'reference_no': 28,
  'title': '주격보어 동사',
  'explanation': 'be, become, seem, look, feel, sound, taste, smell 같은 동사 뒤에는 주어의 상태를 설명하는 형용사 보어가 '
                 '온다.',
  'example': 'This ice cream is delicious. / It feels comfortable.'},
 {'reference_no': 29,
  'title': '목적격보어 동사',
  'explanation': 'make, keep, find, consider, leave 같은 동사는 목적어 뒤에 그 목적어의 상태를 설명하는 보어를 둘 수 있다.',
  'example': 'We found this ice cream delicious.'},
 {'reference_no': 30,
  'title': 'to부정사 목적격보어',
  'explanation': 'allow, ask, want, expect, encourage, require 같은 동사는 목적어 뒤에 to부정사를 목적격보어로 쓴다.',
  'example': 'The changes allowed women to enter the labor market.'},
 {'reference_no': 31,
  'title': '지각동사 목적격보어',
  'explanation': 'see, hear, watch, feel, notice 같은 지각동사는 목적어가 직접 하면 원형부정사나 -ing를, 당하면 p.p.를 '
                 '목적격보어로 쓴다.',
  'example': 'I watched smoke rise. / I heard my name called.'},
 {'reference_no': 32,
  'title': '사역동사 목적격보어',
  'explanation': 'make, have, let은 목적어가 직접 하면 원형부정사를, 당하면 p.p.를 목적격보어로 쓴다.',
  'example': 'This drink made their pains go away. / I had my hair cut.'},
 {'reference_no': 33,
  'title': '동사별 목적격보어 형태',
  'explanation': 'help는 원형부정사나 to부정사, get은 to부정사, keep과 find는 -ing를 목적격보어로 자주 쓴다.',
  'example': 'She found her sister crying.'},
 {'reference_no': 34,
  'title': '대동사',
  'explanation': '앞에 나온 동사나 동사구를 반복하지 않기 위해 do, be동사, 조동사로 대신할 수 있다.',
  'example': 'Some people learn more from failures than they do from successes.'},
 {'reference_no': 35,
  'title': 'to부정사의 명사적 용법',
  'explanation': 'to부정사는 문장에서 주어, 보어, 목적어 역할을 하며 “~하는 것, ~하기”로 해석된다.',
  'example': 'To find the cause is difficult. / I hope to become good friends.'},
 {'reference_no': 36,
  'title': 'to부정사의 형용사적 용법',
  'explanation': 'to부정사는 명사 뒤에서 그 명사를 꾸미며 “~할, ~하는”의 의미를 나타낸다.',
  'example': 'I don’t have much time to spend with my family.'},
 {'reference_no': 37,
  'title': 'to부정사의 부사적 용법',
  'explanation': 'to부정사는 목적, 감정의 원인, 판단의 근거, 결과 등을 나타내며 문장 전체나 형용사·동사를 보충 설명한다.',
  'example': 'We have to buy flour to make bread.'},
 {'reference_no': 38,
  'title': '동명사의 명사 역할',
  'explanation': '동명사는 동사원형 + -ing 형태로 문장에서 주어, 보어, 목적어, 전치사의 목적어 역할을 한다.',
  'example': 'Having companion animals gives more benefits.'},
 {'reference_no': 39,
  'title': 'to부정사를 목적어로 취하는 동사',
  'explanation': 'decide, want, hope, plan, refuse, learn, need 같은 동사는 목적어로 to부정사를 쓴다.',
  'example': 'You must decide to forget your past.'},
 {'reference_no': 40,
  'title': '동명사를 목적어로 취하는 동사',
  'explanation': 'enjoy, avoid, mind, finish, imagine, deny, give up 같은 동사는 목적어로 동명사를 쓴다.',
  'example': 'Some people enjoy getting up early.'},
 {'reference_no': 41,
  'title': 'to부정사와 동명사 모두 가능한 동사',
  'explanation': 'like, love, prefer, hate, start, begin, continue 같은 동사는 목적어로 to부정사와 동명사를 모두 쓸 수 '
                 '있다.',
  'example': 'I like to read books. / I like reading books.'},
 {'reference_no': 42,
  'title': 'to부정사와 동명사의 의미 차이',
  'explanation': 'remember, forget, regret, try, stop은 뒤에 to부정사가 오면 앞으로 할 일, 동명사가 오면 이미 한 일이나 경험을 '
                 '나타내는 경우가 많다.',
  'example': 'I forgot to buy a card. / I forgot buying a card.'},
 {'reference_no': 43,
  'title': '동명사의 관용 표현',
  'explanation': 'feel like, spend 시간, prevent A from, keep A from, be worth, cannot help 같은 표현 '
                 '뒤에는 동명사를 쓴다.',
  'example': 'I feel like going out. / This book is worth reading.'},
 {'reference_no': 44,
  'title': '전치사 to + 동명사',
  'explanation': 'look forward to, object to, be used to, be accustomed to, adjust to 같은 표현의 to는 '
                 '전치사이므로 뒤에 동명사를 쓴다.',
  'example': 'I look forward to seeing you.'},
 {'reference_no': 45,
  'title': 'to부정사의 to',
  'explanation': 'be likely to, be ready to, be willing to, make sure to, be about to, be supposed '
                 'to에서 to는 to부정사의 to이므로 뒤에 동사원형을 쓴다.',
  'example': 'He is likely to succeed.'},
 {'reference_no': 46,
  'title': '현재분사',
  'explanation': '현재분사는 동사원형 + -ing 형태로 능동이나 진행의 의미를 나타내며, 명사를 수식하거나 보어 역할을 한다.',
  'example': 'a boring movie, falling raindrops'},
 {'reference_no': 47,
  'title': '과거분사',
  'explanation': '과거분사는 p.p. 형태로 수동이나 완료의 의미를 나타내며, 명사를 수식하거나 보어 역할을 한다.',
  'example': 'a broken glass, fallen leaves'},
 {'reference_no': 48,
  'title': '분사의 명사 수식',
  'explanation': '분사가 명사를 앞이나 뒤에서 꾸밀 때, 명사가 분사의 동작을 직접 하면 -ing를 쓰고 동작을 당하면 p.p.를 쓴다.',
  'example': 'people working at night / jewels locked in a box'},
 {'reference_no': 49,
  'title': '분사의 보어 역할',
  'explanation': '분사는 주격보어나 목적격보어 자리에서 주어나 목적어의 상태나 동작을 설명한다.',
  'example': 'She stood looking at the painting. / Can I get this gift wrapped?'},
 {'reference_no': 50,
  'title': '분사구문',
  'explanation': '분사구문은 부사절에서 접속사와 주어를 생략하고 동사를 분사 형태로 바꾸어 시간, 이유, 조건, 양보 등의 의미를 간단히 나타낸다.',
  'example': 'Feeling hungry, I looked in the refrigerator.'},
 {'reference_no': 51,
  'title': '분사구문의 생략 과정',
  'explanation': '분사구문은 보통 부사절의 접속사와 주어를 생략하고, 능동이면 동사를 -ing로, 수동이면 being p.p. 또는 p.p.로 바꾼다.',
  'example': 'Because I felt hungry → Feeling hungry.'},
 {'reference_no': 52,
  'title': '명사 수식의 -ing vs p.p.',
  'explanation': '명사와 분사가 능동 관계이면 -ing, 수동 관계이면 p.p.를 쓰며, “~하는”인지 “~된/당한”인지 확인한다.',
  'example': 'a policy restricting the use of plastic bags / purchased goods'},
 {'reference_no': 53,
  'title': '분사구문의 -ing vs p.p.',
  'explanation': '분사구문의 의미상 주어가 동작을 직접 하면 -ing, 동작을 당하면 p.p.를 쓰며, being p.p.에서 being은 자주 생략된다.',
  'example': 'Realizing the importance / Seen from a distance'},
 {'reference_no': 54,
  'title': 'with + 명사 + 분사',
  'explanation': 'with + 명사 + 분사 구조에서 명사가 동작을 직접 하면 -ing, 동작을 당하면 p.p.를 쓴다.',
  'example': 'with everyone sitting together / with her legs crossed'},
 {'reference_no': 55,
  'title': '감정분사 -ing vs p.p.',
  'explanation': '감정을 일으키는 대상은 -ing, 감정을 느끼는 사람은 p.p.를 쓰며, 사람이 감정을 일으키는 경우에는 -ing도 가능하다.',
  'example': 'a fascinating novel / surprised people / He is boring. / He is bored.'},
 {'reference_no': 56,
  'title': '등위접속사',
  'explanation': 'and, but, or 같은 등위접속사는 문법적으로 같은 역할을 하는 단어와 단어, 구와 구, 절과 절을 연결한다.',
  'example': 'We wanted to see a movie, but she didn’t want to.'},
 {'reference_no': 57,
  'title': '상관접속사',
  'explanation': 'both A and B, not only A but also B, either A or B, neither A nor B는 짝을 이루어 쓰이며 '
                 'A와 B에는 같은 품사나 같은 구조가 와야 한다.',
  'example': 'Not only my sister but also I like traveling.'},
 {'reference_no': 58,
  'title': '종속접속사',
  'explanation': '종속접속사는 명사절이나 부사절을 이끌며, 명사절은 주어·목적어·보어 역할을 하고 부사절은 시간, 이유, 조건, 양보 등의 의미를 나타낸다.',
  'example': 'I wonder whether you are busy. / Although it rained, we went out.'},
 {'reference_no': 59,
  'title': '병렬구조',
  'explanation': 'and, but, or 등으로 연결된 말은 앞뒤의 품사나 문법 구조를 같게 맞추어야 하며, to부정사는 뒤에서 to가 생략될 수 있다.',
  'example': 'People work longer, go to meetings, read books, or go out.'},
 {'reference_no': 60,
  'title': '전치사 vs 접속사',
  'explanation': '전치사는 뒤에 명사, 명사구, 동명사를 이끌고, 접속사는 뒤에 주어와 동사가 있는 절을 이끈다.',
  'example': 'Because of the snow / Because the road was closed'},
 {'reference_no': 61,
  'title': '전치사 + 명사 / 접속사 + 절',
  'explanation': 'during, because of, due to, despite, in spite of는 전치사 표현이므로 뒤에 명사구가 오고, while, '
                 'because, although는 접속사이므로 뒤에 절이 온다.',
  'example': 'Despite the rain / Although it rained'},
 {'reference_no': 62,
  'title': '부사절의 주어+be동사 생략',
  'explanation': 'when, while, although 같은 부사절에서 주어가 주절의 주어와 같고 동사가 be동사이면 주어 + be동사를 생략할 수 있다.',
  'example': 'While I am cleaning my room → While cleaning my room'},
 {'reference_no': 63,
  'title': 'during vs for',
  'explanation': 'during은 특정 기간이나 사건 “동안”을 나타내고, for는 기간의 길이를 나타낸다.',
  'example': 'during the summer vacation / for three years'},
 {'reference_no': 64,
  'title': 'by vs until',
  'explanation': 'by는 완료 시한 “~까지는”을 나타내고, until은 어떤 상태나 동작이 계속되는 “~까지”를 나타낸다.',
  'example': 'finish the report by tomorrow / remain valid until June 15'},
 {'reference_no': 65,
  'title': 'beside vs besides',
  'explanation': 'beside는 “~옆에”라는 위치를 나타내고, besides는 “~외에도”라는 추가의 의미를 나타낸다.',
  'example': 'beside me / besides me'},
 {'reference_no': 66,
  'title': '전치사 + 접속사',
  'explanation': 'in that, except that, about whether처럼 전치사 뒤에 접속사가 이어지면 전치사와 접속사가 함께 하나의 의미 단위를 '
                 '이룬다.',
  'example': 'in that they don’t know / about whether it is true'},
 {'reference_no': 67,
  'title': 'that의 지시형용사',
  'explanation': 'that이 명사 앞에서 “저, 그”라는 뜻으로 명사를 꾸미면 지시형용사로 쓰인다.',
  'example': 'Who is that boy?'},
 {'reference_no': 68,
  'title': 'that의 지시대명사',
  'explanation': 'that이 앞의 명사나 문장 내용을 대신하면 지시대명사로 쓰인다.',
  'example': 'That was an amazing performance.'},
 {'reference_no': 69,
  'title': 'that의 부사 용법',
  'explanation': 'that이 형용사나 부사를 꾸며 “그렇게, 그 정도로”라는 뜻을 나타내면 부사로 쓰인다.',
  'example': 'Don’t walk that fast.'},
 {'reference_no': 70,
  'title': '관계대명사',
  'explanation': '관계대명사는 앞의 선행사를 꾸미는 절을 이끌며, 접속사 역할과 대명사 역할을 동시에 한다.',
  'example': 'I met a man who lives in our neighborhood.'},
 {'reference_no': 71,
  'title': '관계대명사의 격',
  'explanation': '관계대명사는 관계사절 안에서 주어 역할을 하면 주격, 목적어 역할을 하면 목적격, 소유 관계를 나타내면 소유격으로 쓴다.',
  'example': 'who / whom / whose'},
 {'reference_no': 72,
  'title': '주격 관계대명사',
  'explanation': '관계대명사가 뒤 절에서 주어 역할을 할 때는 주격 관계대명사를 쓰며, 뒤에는 보통 동사가 바로 온다.',
  'example': 'the building which is the tallest in the world'},
 {'reference_no': 73,
  'title': '목적격 관계대명사',
  'explanation': '관계대명사가 뒤 절에서 목적어 역할을 할 때는 목적격 관계대명사를 쓰며, 뒤 절에는 목적어가 빠진 불완전한 구조가 온다.',
  'example': 'the person whom I met'},
 {'reference_no': 74,
  'title': '소유격 관계대명사',
  'explanation': '소유격 관계대명사 whose는 사람과 사물 모두에 쓸 수 있고, 뒤에 명사가 따라온다.',
  'example': 'the boy whose hair is blond'},
 {'reference_no': 75,
  'title': '관계대명사의 위치',
  'explanation': '관계대명사절은 원칙적으로 꾸미는 선행사 바로 뒤에 오며, 선행사와 너무 멀어지면 의미가 어색해질 수 있다.',
  'example': 'The photo which shows my house'},
 {'reference_no': 76,
  'title': '제한적 용법',
  'explanation': '콤마가 없는 관계사절은 선행사를 특정하는 데 꼭 필요한 정보를 제공하므로 생략하면 의미가 불완전해질 수 있다.',
  'example': 'She has two brothers who became pilots.'},
 {'reference_no': 77,
  'title': '계속적 용법',
  'explanation': '콤마 뒤의 관계사절은 선행사에 대한 추가 설명을 덧붙이는 역할을 하며, 생략해도 문장의 핵심 의미는 남는다.',
  'example': 'She has two brothers, who became pilots.'},
 {'reference_no': 78,
  'title': '콤마 뒤의 which',
  'explanation': '계속적 용법의 which는 앞의 특정 명사뿐 아니라 앞 문장 전체의 내용을 받을 수 있다.',
  'example': 'He failed the test, which surprised everyone.'},
 {'reference_no': 79,
  'title': '관계대명사 what',
  'explanation': 'what은 선행사 the thing(s) which를 포함한 관계대명사로, “~하는 것”이라는 뜻의 명사절을 이끈다.',
  'example': 'What you say is not always true.'},
 {'reference_no': 80,
  'title': '관계부사',
  'explanation': '관계부사는 접속사와 부사의 역할을 동시에 하며, 시간·장소·이유·방법의 선행사를 꾸민다.',
  'example': 'the restaurant where you can eat Greek food'},
 {'reference_no': 81,
  'title': '관계부사 when',
  'explanation': 'when은 time, day, year, age, period 같은 시간 선행사를 꾸민다.',
  'example': 'a beautiful time when flowers begin to bloom'},
 {'reference_no': 82,
  'title': '관계부사 where',
  'explanation': 'where는 place, house, city, area 같은 장소 선행사를 꾸민다.',
  'example': 'the gym where I used to work out'},
 {'reference_no': 83,
  'title': '관계부사 why',
  'explanation': 'why는 이유를 나타내는 the reason을 선행사로 하며, the reason why 형태로 자주 쓰인다.',
  'example': 'the reason why I’m here'},
 {'reference_no': 84,
  'title': '관계부사 how',
  'explanation': 'how는 방법을 나타내며, the way와 how를 함께 쓰지 않고 둘 중 하나만 쓴다.',
  'example': 'the way people interact / how people interact'},
 {'reference_no': 85,
  'title': '목적격 관계대명사의 생략',
  'explanation': '목적격 관계대명사는 전치사가 관계대명사 앞에 오지 않을 때 생략할 수 있다.',
  'example': 'The lady whom you met is our music teacher. → The lady you met is our music '
             'teacher.'},
 {'reference_no': 86,
  'title': '관계부사의 생략',
  'explanation': 'time, day, year, place, reason 같은 선행사가 분명하면 when, where, why 같은 관계부사를 생략할 수 있다.',
  'example': 'I don’t know the reason why the game was canceled. → I don’t know the reason the '
             'game was canceled.'},
 {'reference_no': 87,
  'title': 'that / which / what 구분',
  'explanation': 'that과 which는 앞에 선행사가 있는 관계대명사이고, what은 선행사를 포함하므로 앞에 선행사를 따로 쓰면 안 된다.',
  'example': 'the job that is better / what I asked for'},
 {'reference_no': 88,
  'title': '관계대명사 vs 관계부사',
  'explanation': '관계사 뒤 문장에서 주어, 목적어, 보어가 빠져 있으면 관계대명사를 쓰고, 문장 성분이 완전하면 관계부사를 쓴다.',
  'example': 'countries which have mountains / countries where there are mountains'},
 {'reference_no': 89,
  'title': '전치사 + 관계대명사',
  'explanation': '전치사 뒤에는 관계대명사 whom 또는 which를 쓸 수 있지만, that이나 who는 전치사 바로 뒤에 쓸 수 없다.',
  'example': 'friends from whom I got help'},
 {'reference_no': 90,
  'title': '접속사 that',
  'explanation': '접속사 that은 명사절을 이끌며, 뒤에 완전한 문장이 온다.',
  'example': 'I heard that your injury was not serious.'},
 {'reference_no': 91,
  'title': '관계대명사 that',
  'explanation': '관계대명사 that은 선행사를 꾸미며, 뒤에 주어나 목적어가 빠진 불완전한 문장이 온다.',
  'example': 'the fish that her dad caught'},
 {'reference_no': 92,
  'title': '복합관계대명사',
  'explanation': 'whoever, whichever, whatever는 명사절이나 양보 부사절을 이끌며, 문장에서 주어·목적어·보어 역할을 할 수 있다.',
  'example': 'Whoever breaks this rule will be punished.'},
 {'reference_no': 93,
  'title': '복합관계부사',
  'explanation': 'however, whenever, wherever는 완전한 부사절을 이끌며, “아무리 ~해도, 언제 ~하더라도, 어디에서 ~하더라도”의 뜻을 '
                 '나타낸다.',
  'example': 'Whenever I am in trouble, I consult him.'},
 {'reference_no': 94,
  'title': '셀 수 있는 명사',
  'explanation': '셀 수 있는 명사는 단수일 때 a/an, the, my 같은 한정사가 필요하고, 복수형을 만들 수 있다.',
  'example': 'a book / books, an eye / eyes'},
 {'reference_no': 95,
  'title': '셀 수 없는 명사',
  'explanation': 'information, advice, news, furniture, luggage, equipment 같은 셀 수 없는 명사는 보통 a/an을 '
                 '붙이거나 복수형으로 쓰지 않는다.',
  'example': 'some advice, much information'},
 {'reference_no': 96,
  'title': '지시대명사',
  'explanation': 'this, that, these, those는 사람이나 사물을 대신하며, this/these는 가까운 대상, that/those는 먼 대상을 '
                 '가리킨다.',
  'example': 'This is my book. / These are her students.'},
 {'reference_no': 97,
  'title': 'those who',
  'explanation': 'those who는 “~하는 사람들”이라는 뜻으로 people who와 같은 의미로 쓰인다.',
  'example': 'Those who can’t take the exam will be failed.'},
 {'reference_no': 98,
  'title': '부정대명사',
  'explanation': '부정대명사는 특정하지 않은 사람, 사물, 수량을 나타내며 one, other, another, some, any, all, both, '
                 'either, neither 등이 있다.',
  'example': 'Can you show me the white one?'},
 {'reference_no': 99,
  'title': 'many/much',
  'explanation': 'many는 셀 수 있는 복수명사와 쓰고, much는 셀 수 없는 명사와 쓴다.',
  'example': 'many students / much water'},
 {'reference_no': 100,
  'title': 'few/little',
  'explanation': 'few는 셀 수 있는 복수명사와 쓰고, little은 셀 수 없는 명사와 쓴다.',
  'example': 'few books / little interest'},
 {'reference_no': 101,
  'title': 'a few/a little',
  'explanation': 'a few는 셀 수 있는 복수명사와 쓰여 “약간 있는”의 뜻이고, a little은 셀 수 없는 명사와 쓰여 “약간 있는”의 뜻이다.',
  'example': 'a few friends / a little money'},
 {'reference_no': 102,
  'title': 'many a + 단수명사',
  'explanation': 'many a 뒤에는 단수명사가 오지만 의미는 “많은 ~”이므로 복수 의미를 나타낸다.',
  'example': 'Many a student does volunteer work.'},
 {'reference_no': 103,
  'title': '재귀대명사',
  'explanation': '재귀대명사는 주어와 목적어가 같은 대상을 가리킬 때 목적어 자리에 쓴다.',
  'example': 'He found himself lying in bed.'},
 {'reference_no': 104,
  'title': '강조용 재귀대명사',
  'explanation': '재귀대명사는 주어나 목적어를 강조하여 “직접, 스스로”라는 의미를 나타낼 수 있다.',
  'example': 'I myself found it rather dull.'},
 {'reference_no': 105,
  'title': '재귀대명사 관용 표현',
  'explanation': 'by oneself, for oneself, enjoy oneself, help oneself to, make oneself at home 같은 '
                 '표현은 재귀대명사와 함께 자주 쓰인다.',
  'example': 'Please help yourself to some cookies.'},
 {'reference_no': 106,
  'title': 'one / the other',
  'explanation': '둘 중 하나는 one, 나머지 하나는 the other로 나타낸다.',
  'example': 'One is standard and the other is Creole.'},
 {'reference_no': 107,
  'title': 'one / another / the other',
  'explanation': '셋 중 하나는 one, 다른 하나는 another, 나머지 하나는 the other로 나타낸다.',
  'example': 'One is blue, another is red, and the other is green.'},
 {'reference_no': 108,
  'title': 'one / others / the others',
  'explanation': '여럿 중 일부를 말할 때 one이나 some을 쓰고, 남은 것 중 일부는 others, 남은 전부는 the others로 나타낸다.',
  'example': 'Some are easy, others are difficult, and the others are unknown.'},
 {'reference_no': 109,
  'title': 'another',
  'explanation': 'another는 “또 다른 하나”라는 뜻으로 단수명사 앞에 쓰이거나 단독으로 쓰인다.',
  'example': 'another book / another'},
 {'reference_no': 110,
  'title': 'other',
  'explanation': 'other는 “다른”이라는 뜻으로 복수명사나 셀 수 없는 명사 앞에 쓴다.',
  'example': 'other students / other information'},
 {'reference_no': 111,
  'title': 'the other',
  'explanation': 'the other는 “나머지 하나” 또는 “나머지 쪽”처럼 정해진 대상을 가리킨다.',
  'example': 'the other hand'},
 {'reference_no': 112,
  'title': 'one vs it',
  'explanation': 'one은 앞에 나온 명사와 같은 종류의 불특정 대상을 대신하고, it은 앞에 나온 바로 그 특정 대상을 대신한다.',
  'example': 'I want to buy one. / I have to find it.'},
 {'reference_no': 113,
  'title': 'some/any/every/no + thing/body/one',
  'explanation': 'something, anybody, everyone, nothing 같은 표현은 특정하지 않은 사물이나 사람을 가리키는 부정대명사로 쓰인다.',
  'example': 'I didn’t find anything suitable.'},
 {'reference_no': 114,
  'title': '부정대명사의 후치수식',
  'explanation': 'somebody, anything, nothing 같은 부정대명사를 형용사나 to부정사가 꾸밀 때는 뒤에서 수식한다.',
  'example': 'anybody young / something to drink'},
 {'reference_no': 115,
  'title': 'all/most/half/both + of',
  'explanation': 'all, most, half, both 뒤에 대명사나 한정된 명사가 오면 of를 쓰고, 일반 명사가 오면 of 없이 쓸 수 있다.',
  'example': 'all of his books / all books'},
 {'reference_no': 116,
  'title': 'either',
  'explanation': 'either는 둘 중 어느 하나를 뜻하고, not either는 “둘 다 아니다”의 의미로 쓰인다.',
  'example': 'either way'},
 {'reference_no': 117,
  'title': 'neither',
  'explanation': 'neither는 둘 다 아님을 나타내며, 의미상 no와 비슷하다.',
  'example': 'Neither of us has ever been to Europe.'},
 {'reference_no': 118,
  'title': '형용사의 역할',
  'explanation': '형용사는 명사를 앞이나 뒤에서 수식하거나, 보어 자리에서 주어나 목적어의 상태를 설명한다.',
  'example': 'This is a difficult question. / This ice cream is delicious.'},
 {'reference_no': 119,
  'title': '후치수식 형용사',
  'explanation': 'something, anything, nothing 같은 부정대명사를 형용사가 꾸밀 때는 보통 형용사를 뒤에 둔다.',
  'example': 'something interesting'},
 {'reference_no': 120,
  'title': '보어로만 쓰는 형용사',
  'explanation': 'afraid, alive, alone, ashamed, asleep, aware, content, glad, unable 같은 형용사는 주로 '
                 '보어로 쓰이고 명사 앞에서 직접 꾸미는 용법은 피한다.',
  'example': 'The baby is asleep. / a sleeping baby'},
 {'reference_no': 121,
  'title': '부사의 역할',
  'explanation': '부사는 동사, 형용사, 다른 부사, 문장 전체를 수식하여 동작의 방식, 정도, 시간, 빈도, 화자의 판단 등을 나타낸다.',
  'example': 'speak clearly / really great / very well / Fortunately, ~'},
 {'reference_no': 122,
  'title': '부사의 형태',
  'explanation': '대부분의 부사는 형용사에 -ly를 붙여 만들지만, friendly, lovely, costly처럼 -ly로 끝나도 형용사인 단어가 있으므로 '
                 '주의한다.',
  'example': 'usual → usually / angry → angrily'},
 {'reference_no': 123,
  'title': '빈도부사',
  'explanation': '빈도부사는 얼마나 자주 일어나는지를 나타내며, 보통 일반동사 앞이나 be동사·조동사 뒤에 온다.',
  'example': 'always, usually, often, sometimes, seldom, rarely, hardly, never'},
 {'reference_no': 124,
  'title': '형용사 vs 부사',
  'explanation': '형용사는 명사나 보어 자리에 쓰이고, 부사는 동사·형용사·다른 부사·문장 전체를 수식한다.',
  'example': 'mechanical skill / study mechanically'},
 {'reference_no': 125,
  'title': '보어 자리의 형용사',
  'explanation': 'be동사나 감각동사 뒤에서 주어의 상태를 설명할 때는 부사가 아니라 형용사를 쓴다.',
  'example': 'The Queen of Denmark is present.'},
 {'reference_no': 126,
  'title': '부사의 수식 대상',
  'explanation': '부사는 동사, 형용사, 다른 부사를 수식하므로 무엇을 꾸미는지 확인해서 형용사와 구분한다.',
  'example': 'explain appropriately / extremely busy / very fast'},
 {'reference_no': 127,
  'title': '형용사/부사 모두 가능한 단어',
  'explanation': 'fast, hard, late, early, high, near, deep, short 같은 단어는 문맥에 따라 형용사나 부사로 모두 쓰일 수 '
                 '있다.',
  'example': 'a fast car / run fast'},
 {'reference_no': 128,
  'title': '의미가 다른 형용사와 부사',
  'explanation': 'alone/lonely, late/lately, hard/hardly, near/nearly, high/highly처럼 형태가 비슷해도 뜻이 '
                 '달라지는 단어는 문맥으로 구분한다.',
  'example': 'work hard / hardly work'},
 {'reference_no': 129,
  'title': '부정 의미를 가진 부사',
  'explanation': 'hardly, scarcely, seldom, rarely 같은 부사는 자체에 부정 의미가 있으므로 no, never, without 같은 다른 '
                 '부정 표현과 함께 쓰지 않는다.',
  'example': 'He hardly looked like a famous psychiatrist.'},
 {'reference_no': 130,
  'title': '부분 부정',
  'explanation': 'not all, not every, not always, not necessarily는 “모두/항상/반드시 ~한 것은 아니다”라는 부분 부정을 '
                 '나타낸다.',
  'example': 'This is not always true.'},
 {'reference_no': 131,
  'title': '전체 부정',
  'explanation': 'none, no, never, neither, not ~ at all은 전체를 부정하여 “아무도/전혀/둘 다 아니다”의 뜻을 나타낸다.',
  'example': 'none of my friends'},
 {'reference_no': 132,
  'title': 'the + 형용사',
  'explanation': 'the + 형용사는 “~한 사람들”이라는 뜻으로 복수 보통명사처럼 쓰일 수 있다.',
  'example': 'the rich, the poor, the young'},
 {'reference_no': 133,
  'title': 'the + 추상형용사',
  'explanation': 'the + 형용사는 문맥에 따라 추상적인 개념을 나타낼 수도 있다.',
  'example': 'the true, the false, the unknown'},
 {'reference_no': 134,
  'title': '원급 비교',
  'explanation': 'as + 형용사/부사의 원급 + as는 두 대상의 정도가 같음을 나타내며, 부정문에서는 not as/so + 원급 + as로 “~만큼 …하지 '
                 '않다”의 뜻을 나타낸다.',
  'example': 'as poisonous as a cobra / not as tall as my mother'},
 {'reference_no': 135,
  'title': '비교급',
  'explanation': '비교급 + than은 두 대상의 정도가 서로 다를 때 사용하며, 형용사나 부사의 비교급 형태를 쓴다.',
  'example': 'The previous test was easier than this one.'},
 {'reference_no': 136,
  'title': '최상급',
  'explanation': 'the + 최상급 + in/of/that절은 셋 이상 중 가장 정도가 높거나 낮은 대상을 나타낸다.',
  'example': 'She is the most generous person in the neighborhood.'},
 {'reference_no': 137,
  'title': '원급·비교급·최상급 구별',
  'explanation': 'as와 as 사이에는 원급을 쓰고, than 앞에는 비교급을 쓰며, 셋 이상 중 최고나 최저를 나타내면 최상급을 쓴다.',
  'example': 'as hard as / more popular than / the least painful'},
 {'reference_no': 138,
  'title': '비교급과 최상급의 불규칙 변화',
  'explanation': 'many/much-more-most, good/well-better-best, bad/ill-worse-worst, '
                 'far-farther/further-farthest/furthest처럼 불규칙한 변화는 형태를 따로 확인해야 한다.',
  'example': 'the best play / the most time'},
 {'reference_no': 139,
  'title': '비교구문의 병렬구조',
  'explanation': '비교구문에서는 비교되는 두 대상의 품사나 구조가 서로 같아야 하며, 생략된 반복 표현도 같은 구조로 이해해야 한다.',
  'example': 'I like watching basketball more than playing basketball.'},
 {'reference_no': 140,
  'title': '비교대상 대신 쓰는 대명사',
  'explanation': '비교구문에서 앞의 명사나 동사의 반복을 피하기 위해 that, those, one, ones, do, be동사, 조동사를 사용할 수 있다.',
  'example': 'The number of deaths was larger than that of births.'},
 {'reference_no': 141,
  'title': '비교구문의 형용사 vs 부사',
  'explanation': '비교 표현이 명사나 보어를 설명하면 형용사, 동사나 문장 전체를 수식하면 부사를 써야 한다.',
  'example': 'not as powerful as / speak more fluently than'},
 {'reference_no': 142,
  'title': 'the 비교급, the 비교급',
  'explanation': 'the + 비교급, the + 비교급은 “~하면 할수록 더 …하다”라는 뜻으로, 앞뒤 문장의 비교급 구조를 맞춘다.',
  'example': 'The rougher the surface is, the more friction is produced.'},
 {'reference_no': 143,
  'title': '원급을 이용한 최상급 표현',
  'explanation': '비교급 + than any other + 단수명사, No other + 비교급 than, No other + as/so 원급 as는 모두 '
                 '최상급의 의미를 나타낸다.',
  'example': 'He is happier than any other man in the world.'},
 {'reference_no': 144,
  'title': '비교 관용표현',
  'explanation': 'as 원급 as possible은 “가능한 한 ~하게”, no more than은 “고작 ~에 불과한”, no less than은 “무려 '
                 '~만큼”의 뜻으로 쓰인다.',
  'example': 'Use recycled products as much as possible.'},
 {'reference_no': 145,
  'title': '배수 표현',
  'explanation': 'twice, three times, half 같은 배수 표현은 배수 + as 원급 as, 배수 + 비교급 than, 배수 + the 명사 of '
                 '형태로 쓸 수 있다.',
  'example': 'twice as heavy as white / three times larger than before'},
 {'reference_no': 146,
  'title': '원급 수식어',
  'explanation': 'almost, exactly, just, nearly는 원급 비교 표현을 수식하여 “거의/정확히/딱 ~만큼”의 의미를 더한다.',
  'example': 'nearly as tall as'},
 {'reference_no': 147,
  'title': '비교급 수식어',
  'explanation': 'much, still, far, even, a lot, a great deal은 비교급 앞에서 “훨씬, 더욱”의 의미로 비교급을 강조한다.',
  'example': 'much more popular / far more quickly'},
 {'reference_no': 148,
  'title': '최상급 수식어',
  'explanation': 'much, by far, the very, quite는 최상급을 강조할 때 쓰이며, very는 보통 the very best처럼 the와 함께 '
                 '쓴다.',
  'example': 'by far the best / the very best'},
 {'reference_no': 149,
  'title': '현재시제',
  'explanation': '현재시제는 현재의 상태, 반복되는 습관, 일반적 사실이나 진리를 나타낸다.',
  'example': 'I take swimming lessons every morning. / The Moon revolves around the Earth.'},
 {'reference_no': 150,
  'title': '과거시제',
  'explanation': '과거시제는 과거의 특정 시점에 일어난 일이나 과거의 상태를 나타낸다.',
  'example': 'Last Saturday, he invited Cathy to his party.'},
 {'reference_no': 151,
  'title': '미래시제',
  'explanation': '미래시제는 앞으로 일어날 일이나 미래의 예측을 나타내며 보통 will + 동사원형을 사용한다.',
  'example': 'The party will be at my house.'},
 {'reference_no': 152,
  'title': '현재진행시제',
  'explanation': '현재진행시제는 am/is/are + -ing 형태로 현재 말하는 순간 진행 중인 일을 나타낸다.',
  'example': 'He is talking to his mom on the phone.'},
 {'reference_no': 153,
  'title': '과거진행시제',
  'explanation': '과거진행시제는 was/were + -ing 형태로 과거의 특정 시점에 진행 중이던 일을 나타낸다.',
  'example': 'My father was preparing dinner when I got home.'},
 {'reference_no': 154,
  'title': '미래진행시제',
  'explanation': '미래진행시제는 will be + -ing 형태로 미래의 특정 시점에 진행 중일 일을 나타낸다.',
  'example': 'I will be watching a movie at noon.'},
 {'reference_no': 155,
  'title': '현재완료시제',
  'explanation': '현재완료는 have/has + p.p. 형태로 과거에 일어난 일이 현재와 관련될 때 쓰며 경험, 계속, 완료, 결과를 나타낸다.',
  'example': 'I have met him twice. / I have just heard the news. / I have lost my wallet.'},
 {'reference_no': 156,
  'title': '과거완료시제',
  'explanation': '과거완료는 had + p.p. 형태로 과거의 한 시점보다 더 먼저 일어난 일을 나타낸다.',
  'example': 'Julia had worked for the company for two years when I met her.'},
 {'reference_no': 157,
  'title': '미래완료시제',
  'explanation': '미래완료는 will have + p.p. 형태로 미래의 어느 시점까지 완료될 일을 나타낸다.',
  'example': 'I will have lived here for ten years next year.'},
 {'reference_no': 158,
  'title': '현재완료진행시제',
  'explanation': '현재완료진행은 have/has been + -ing 형태로 과거부터 현재까지 계속 진행 중인 일을 강조한다.',
  'example': 'I have been studying hard since seven o’clock.'},
 {'reference_no': 159,
  'title': '과거완료진행시제',
  'explanation': '과거완료진행은 had been + -ing 형태로 과거의 어느 시점까지 계속 진행되어 온 일을 나타낸다.',
  'example': 'We had been looking for a house for six months before we found one.'},
 {'reference_no': 160,
  'title': '미래완료진행시제',
  'explanation': '미래완료진행은 will have been + -ing 형태로 미래의 어느 시점까지 계속 진행되고 있을 일을 나타낸다.',
  'example': 'This time next year I will have been writing my book for five years.'},
 {'reference_no': 161,
  'title': '과거시제 vs 현재완료',
  'explanation': '과거시제는 yesterday, ago, last, in + 과거연도, when처럼 분명한 과거 시점과 쓰고, 현재완료는 since, for, '
                 'so far, recently, already, yet처럼 현재와 관련된 표현과 자주 쓰인다.',
  'example': 'In 1964, Smith published another novel.'},
 {'reference_no': 162,
  'title': '과거완료',
  'explanation': '두 과거 사건이 있을 때 더 먼저 일어난 일은 과거완료로, 나중에 일어난 일은 과거시제로 나타낸다.',
  'example': 'When I entered the auditorium, the lecture had already begun.'},
 {'reference_no': 163,
  'title': '대과거',
  'explanation': '과거의 한 사건보다 더 이전에 일어난 일을 강조할 때 had + p.p.를 사용한다.',
  'example': 'I gave her a ring she had given me fifty years before.'},
 {'reference_no': 164,
  'title': '시간·조건 부사절의 미래',
  'explanation': 'when, before, after, until, as soon as, if, unless 같은 시간·조건 부사절에서는 미래의 일도 will '
                 '대신 현재시제로 나타낸다.',
  'example': 'If the weather is good, he will go to an amusement park.'},
 {'reference_no': 165,
  'title': '명사절의 미래',
  'explanation': 'when이나 if가 “언제, ~인지 아닌지”라는 뜻으로 명사절을 이끌 때는 미래 의미를 will로 나타낼 수 있다.',
  'example': 'I doubt if anyone will be interested in the program.'},
 {'reference_no': 166,
  'title': '현재시제의 다양한 의미',
  'explanation': '현재시제는 현재 사실, 현재 습관, 불변의 진리, 시간·조건 부사절의 미래, 확정된 가까운 미래를 나타낼 수 있다.',
  'example': 'The Earth moves around the Sun. / This train leaves tomorrow.'},
 {'reference_no': 167,
  'title': 'will',
  'explanation': 'will은 단순한 미래 예측이나 말하는 순간의 의지를 나타낸다.',
  'example': 'The Asian Games will start on August 18.'},
 {'reference_no': 168,
  'title': 'be going to',
  'explanation': 'be going to는 예정된 계획이나 현재 상황을 근거로 한 가까운 미래를 나타낸다.',
  'example': 'Look at those dark clouds — it is going to rain soon.'},
 {'reference_no': 169,
  'title': '현재진행형의 미래',
  'explanation': '현재진행형은 이미 정해진 개인적인 계획이나 약속을 나타낼 수 있다.',
  'example': 'I am meeting some friends for dinner tonight.'},
 {'reference_no': 170,
  'title': '현재시제의 미래',
  'explanation': '현재시제는 시간표, 일정, 프로그램처럼 확정된 미래를 나타낼 수 있다.',
  'example': 'The next movie shows in 10 minutes.'},
 {'reference_no': 171,
  'title': 'be about to',
  'explanation': 'be about to는 “막 ~하려고 하다”라는 뜻으로 아주 가까운 미래를 나타낸다.',
  'example': 'The professor is about to give a lecture.'},
 {'reference_no': 172,
  'title': 'be/have/do 조동사',
  'explanation': 'be는 진행형과 수동태, have는 완료형, do는 부정문·의문문·동사 강조·도치 구문을 만드는 조동사로 쓰인다.',
  'example': 'He is studying. / I have ordered. / Never did I feel such sadness.'},
 {'reference_no': 173,
  'title': 'can/could',
  'explanation': 'can과 could는 능력, 가능성, 허가, 요청을 나타내며 could는 can보다 더 공손하거나 약한 의미로 쓰일 수 있다.',
  'example': 'My son can sing. / You could borrow my calculator.'},
 {'reference_no': 174,
  'title': 'may/might',
  'explanation': 'may와 might는 허가나 가능성·추측을 나타내며, might는 may보다 가능성이 낮거나 더 조심스러운 추측을 나타낸다.',
  'example': 'May I ask you a question? / Julia might be at home.'},
 {'reference_no': 175,
  'title': 'will/would',
  'explanation': 'will은 미래나 의지를 나타내고, would는 공손한 요청이나 과거의 습관을 나타낼 수 있다.',
  'example': 'You will see the sunrise. / I would climb the mountain with my family.'},
 {'reference_no': 176,
  'title': 'should/ought to',
  'explanation': 'should와 ought to는 충고, 의무, 당연한 일을 나타내며 “~해야 한다, ~하는 것이 좋다”로 해석된다.',
  'example': 'You should renew your passport.'},
 {'reference_no': 177,
  'title': 'must/have to',
  'explanation': 'must와 have to는 강한 의무를 나타내며, must는 화자의 판단이 강하고 have to는 외부 상황에 따른 의무를 나타내는 경우가 '
                 '많다.',
  'example': 'Cars must not be parked here.'},
 {'reference_no': 178,
  'title': 'need',
  'explanation': 'need는 일반동사와 조동사로 모두 쓰이며, 조동사일 때는 주로 부정문과 의문문에서 need + 동사원형 형태로 쓰인다.',
  'example': 'You need not come to the meeting.'},
 {'reference_no': 179,
  'title': 'had better/would rather',
  'explanation': 'had better는 “~하는 것이 좋겠다”라는 경고나 충고를 나타내고, would rather는 “차라리 ~하겠다”라는 선호를 나타낸다.',
  'example': 'You had better exercise. / I would rather stay home.'},
 {'reference_no': 180,
  'title': '가능성·추측 조동사',
  'explanation': 'must, will, would, should, can, could, may, might는 확신의 정도에 따라 추측을 나타내며 must가 가장 '
                 '강하고 may/might는 약한 추측을 나타낸다.',
  'example': 'She must be tired. / Julia might be at home.'},
 {'reference_no': 181,
  'title': '조동사 + have p.p.',
  'explanation': '조동사 + have p.p.는 과거 사실에 대한 추측, 후회, 비난, 가능성을 나타낸다.',
  'example': 'She should have asked me before she used my phone.'},
 {'reference_no': 182,
  'title': '주장·명령·요구·제안 뒤 should',
  'explanation': 'suggest, demand, insist, recommend, request, order, propose 같은 주장·명령·요구·제안 동사 뒤 '
                 'that절에서는 should + 동사원형을 쓰며 should는 생략될 수 있다.',
  'example': 'He recommends that every student study regularly.'},
 {'reference_no': 183,
  'title': '조동사 관용표현',
  'explanation': 'cannot help v-ing, cannot but + 동사원형, have no choice but to-v는 “~하지 않을 수 없다”의 '
                 '의미를 나타낸다.',
  'example': 'I couldn’t help bursting into tears.'},
 {'reference_no': 184,
  'title': 'if 가정법 과거',
  'explanation': 'if 가정법 과거는 현재 사실과 반대되는 일을 가정할 때 쓰며, If + 주어 + 과거동사, 주어 + would/could/might + '
                 '동사원형 형태를 사용한다.',
  'example': 'If I had a day off tomorrow, I would go to the beach.'},
 {'reference_no': 185,
  'title': 'if 가정법 과거완료',
  'explanation': 'if 가정법 과거완료는 과거 사실과 반대되는 일을 가정할 때 쓰며, If + 주어 + had p.p., 주어 + would/could/might '
                 'have p.p. 형태를 사용한다.',
  'example': 'If Jenny had invited me, I would have gone to her birthday party.'},
 {'reference_no': 186,
  'title': '혼합가정법',
  'explanation': 'if절은 과거 사실의 반대를, 주절은 현재 결과를 나타낼 때 If + 주어 + had p.p., 주어 + would/could/might + '
                 '동사원형 형태를 쓴다.',
  'example': 'If we had had rice for lunch instead of noodles, we wouldn’t be hungry now.'},
 {'reference_no': 187,
  'title': 'I wish + 가정법 과거',
  'explanation': 'I wish 뒤에 가정법 과거가 오면 현재 이루어지지 않은 소망이나 현재 사실과 반대되는 아쉬움을 나타낸다.',
  'example': 'I wish that I had more time to talk with him.'},
 {'reference_no': 188,
  'title': 'I wish + 가정법 과거완료',
  'explanation': 'I wish 뒤에 가정법 과거완료가 오면 과거에 이루어지지 않은 일에 대한 후회나 아쉬움을 나타낸다.',
  'example': 'I wish that I had had time to read the books I bought.'},
 {'reference_no': 189,
  'title': 'as if + 가정법 과거',
  'explanation': 'as if 뒤에 가정법 과거가 오면 현재 사실과 반대되는 상황을 마치 사실처럼 말하는 의미를 나타낸다.',
  'example': 'His English sounds perfect, as if he were from England.'},
 {'reference_no': 190,
  'title': 'as if + 가정법 과거완료',
  'explanation': 'as if 뒤에 가정법 과거완료가 오면 과거 사실과 반대되는 상황을 마치 사실처럼 말하는 의미를 나타낸다.',
  'example': 'She looked as if she had lain in the sun too long.'},
 {'reference_no': 191,
  'title': '가정법 vs 직설법',
  'explanation': '실현 가능성이 낮거나 사실과 반대되는 가정은 가정법을 쓰고, 실제로 가능하거나 사실에 가까운 조건은 직설법을 쓴다.',
  'example': 'If it snowed tonight, it would be fantastic. / If it snows tonight, it’ll be '
             'fantastic.'},
 {'reference_no': 192,
  'title': 'if 생략 도치',
  'explanation': '가정법에서 if가 생략되면 were, had, should가 주어 앞으로 나와 Were/Had/Should + 주어 형태가 된다.',
  'example': 'Should you need further assistance, please call the number below.'},
 {'reference_no': 193,
  'title': 'had + 주어 + p.p. 도치',
  'explanation': '가정법 과거완료에서 if가 생략되면 Had + 주어 + p.p. 형태로 도치된다.',
  'example': 'Had she gotten proper care, she wouldn’t have died.'},
 {'reference_no': 194,
  'title': 'were + 주어 도치',
  'explanation': '가정법 과거에서 if가 생략되면 Were + 주어 형태로 도치될 수 있다.',
  'example': 'Were I in your position, I would quit that job.'},
 {'reference_no': 195,
  'title': 'if + were to',
  'explanation': 'if + were to는 실현 가능성이 매우 낮거나 거의 불가능한 미래의 일을 가정할 때 쓴다.',
  'example': 'If I were to be young again, I would be a teacher.'},
 {'reference_no': 196,
  'title': 'if + should',
  'explanation': 'if + should는 가능성이 낮거나 우연히 일어날 수 있는 미래 일을 가정할 때 쓰며, 공손한 요청이나 제안에도 쓰일 수 있다.',
  'example': 'If you should finish today, give me a ring.'},
 {'reference_no': 197,
  'title': 'It is time that + 가정법 과거',
  'explanation': 'It is time that 뒤에는 현재 해야 할 일을 아직 하지 않았다는 의미로 과거동사를 쓴다.',
  'example': 'It is time that you started looking for a job.'},
 {'reference_no': 198,
  'title': 'Without/But for + 가정법 과거',
  'explanation': 'Without이나 But for가 현재 사실과 반대되는 조건을 나타낼 때는 if it were not for와 같은 의미로 쓴다.',
  'example': 'Without water, no living things could exist.'},
 {'reference_no': 199,
  'title': 'Without/But for + 가정법 과거완료',
  'explanation': 'Without이나 But for가 과거 사실과 반대되는 조건을 나타낼 때는 if it had not been for와 같은 의미로 쓴다.',
  'example': 'Without your help, I couldn’t have overcome my problems.'},
 {'reference_no': 200,
  'title': '가정법 해석 기준',
  'explanation': '가정법은 실제 사실이 아니라 반대 상황이나 가능성이 낮은 상황을 말하므로, 해석할 때 “만약 ~라면 …할 텐데”, “만약 ~했더라면 …했을 '
                 '텐데”처럼 아쉬움이나 상상을 살려 해석한다.',
  'example': 'If I had known the truth, I would have told you.'}]

# Backward-compatible alias for earlier analyzer code/imports.
GRAMMAR_REFERENCE_ITEMS = GRAMMAR_REFERENCE


def grammar_reference_prompt() -> str:
    lines = [
        "GRAMMAR REFERENCE LIST FOR grammar_points:",
        "Use these titles and reference numbers when a sentence clearly matches.",
        "Do not force grammar_points when no listed grammar item clearly applies.",
    ]
    for item in GRAMMAR_REFERENCE:
        example = f" Example: {item['example']}" if item.get('example') else ""
        lines.append(
            f"{item['reference_no']}. {item['title']}: {item['explanation']}{example}"
        )
    return "\n".join(lines)
